Repository team-yeo-eun-pa/greenFire-frontend, pull requests merged in 2024-06, with the labels that each got.

#39 #38 관리자 회원관리 조회
  .env
  src/App.js
  src/apis/AdminMemberAPICalls.js
  src/apis/AdminNoticeAPICalls.js
  src/components/common/SellerPageNavBar.js
  src/layouts/AdminPageLayout.js
  src/modules/AdminMemberModules.js
  src/modules/NoticeModules.js
  src/modules/index.js
  src/pages/admin/AdminMemberView.js
  src/pages/admin/AdminNotices.js
  src/store.js
Labels: ✨기능

#40 #37 랜딩 페이지 작업
  package-lock.json
  package.json
  public/category1.png
  public/category2.png
  public/category3.png
  public/category4.png
  public/greenFire_logo.png
  src/App.js
  src/components/common/ScrollToTop.js
  src/components/items/MainItem.js
  src/components/items/StoreCategoryButtons.js
  src/layouts/AdminPageLayout.js
  src/pages/Main.js
  src/pages/error/Error.js
Labels: 🎨React/CSS

#43 #32 회원 마이페이지 프로필 조회
  src/App.js
  src/apis/Challenge/InquiryAPI.js
  src/apis/MemberAPICalls.js
  src/components/common/NavBar.js
  src/components/common/SellerPageNavBar.js
  src/components/common/UserPageNavBar.js
  src/components/items/ChallengeItem.js
  src/components/items/MemberProfileItem.js
  src/components/items/challenge/ChallengeItem.js
  src/layouts/UserPageLayout.js
  src/pages/challenge/ChallengeMain.js
  src/pages/member/MemberProfile.js
Labels: ✨기능

#42 #41 관리자 카테고리 조회
  package.json
  src/App.js
  src/apis/AdminCategoryAPICalls.js
  src/modules/AdminCategoryModules.js
  src/modules/index.js
  src/pages/admin/AdminCategory.js
Labels: ✨기능

#45 #41 관리자 카테고리 조회 등록 삭제
  src/App.js
  src/apis/AdminCategoryAPICalls.js
  src/modules/AdminCategoryModules.js
  src/pages/admin/AdminCategory.js
Labels: ✨기능

#48 #47 자동 로그아웃 기능 추가
  src/apis/api.js
Labels: 🐞버그

#51 #44 판매자 마이스토어 조회 / 관리자 권한 체크
  src/App.js
  src/apis/MemberAPICalls.js
  src/apis/SellerAPICalls.js
  src/components/common/NavBar.js
  src/components/common/SellerPageNavBar.js
  src/components/items/StoreProfile.js
  src/components/items/StoreProfileItem.js
  src/layouts/SellerPageLayout.js
  src/modules/SellerModules.js
  src/modules/index.js
  src/pages/seller/MyStoreList.js
  src/pages/seller/MyStoreMain.js
Labels: ✨기능

#50 #49 관리자 정지회원 조회 및 정지해제
  src/App.js
  src/apis/AdminReportAPICalls.js
  src/modules/AdminReportModules.js
  src/modules/index.js
  src/pages/admin/AdminReport.js
Labels: ✨feat

#55 #49 관리자 신고 상세조회와 리팩토링
  src/App.js
  src/apis/AdminReportAPICalls.js
  src/components/common/AdminPageNavBar.js
  src/components/items/TableEx.js
  src/modules/AdminReportModules.js
  src/modules/index.js
  src/pages/admin/AdminMemberView.js
  src/pages/admin/AdminNotices.js
  src/pages/admin/AdminReport.js
Labels: ✨feat, 🔨refactor

#56 #46 결제 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/pages/error/Error.js
  src/pages/order/OrderPage.js
  src/pages/payment/CheckoutPage.js
  src/pages/payment/FailPage.js
  src/pages/payment/SuccessPage.js
Labels: ✨feat, 🎨React/CSS

#62 #61 관리자 카테고리 조회 URL 설정변경
  src/App.js
  src/apis/AdminCategoryAPICalls.js
  src/apis/ReportAPICalls.js
  src/components/items/ReportButton.js
  src/modules/ReportModules.js
  src/modules/index.js
  src/pages/admin/ReportPage.js
  src/style.css
Labels: ⚙set, 🔨refactor

#66 [Feature] 회원신고 기능
  src/apis/ReportAPICalls.js
  src/components/items/ReportButton.js
  src/pages/admin/ReportPage.js
Labels: ✨feat

#73 #72 테이블과 관리자 회원관리 디자인 변경
  src/App.js
  src/apis/AdminNoticeAPICalls.js
  src/apis/AdminReportAPICalls.js
  src/apis/ReportAPICalls.js
  src/components/items/TableEx.js
  src/components/items/TextEditor.js
  src/modules/AdminReportModules.js
  src/modules/MemberModules.js
  src/modules/NoticeModules.js
  src/pages/admin/AdminCreateNotice.js
  src/pages/admin/AdminMemberView.js
  src/pages/admin/AdminNotices.js
  src/pages/admin/AdminReport.js
  src/pages/admin/MemberNotice.js
  src/pages/admin/ReportPage.js
  src/style.css
Labels: 🎨React/CSS

#75 [Refactor] 관리자 정지된 회원 조회 및 상세조회
  src/apis/AdminReportAPICalls.js
  src/components/items/TextEditor.js
  src/modules/AdminReportModules.js
  src/pages/admin/AdminCreateNotice.js
  src/pages/admin/AdminNotices.js
  src/pages/admin/AdminReport.js
  src/style.css
Labels: 🔨refactor

#78 [BUG] 깃에 추가 안되었던 파일 추가
  src/pages/admin/AdminNotice.js
Labels: 🐞bug

#79 [Feature] 카테고리 수정기능 효과 추가
  src/App.js
  src/apis/AdminCategoryAPICalls.js
  src/components/common/AdminPageNavBar.js
  src/modules/AdminCategoryModules.js
  src/pages/admin/AdminCategory.js
  src/pages/admin/AdminReport.js
  src/style.css
Labels: ✨feat, 🔨refactor

#82 #59 회원 주문 내역 조회
  src/App.js
  src/apis/OrderAPICalls.js
  src/components/common/UserPageNavBar.js
  src/components/items/Order.js
  src/modules/OrderModules.js
  src/modules/index.js
  src/pages/order/Order.js
  src/pages/order/OrderDetails.js
  src/pages/order/OrderList.js
  src/pages/order/OrderPage.js
  src/pages/payment/PaymentCancelPage.js
  src/style.css
Labels: ✨feat, 🎨React/CSS

#84 #70 회원 마이페이지 신규 입점 신청 조회/등록/수정/취소
  package-lock.json
  package.json
  src/App.js
  src/apis/ApplyAPICalls.js
  src/components/common/UserPageNavBar.js
  src/components/form/ApplyForm.js
  src/components/items/CustomTable.js
  src/components/items/LoginModal.js
  src/custom.scss
  src/modules/ApplyModules.js
  src/modules/index.js
  src/pages/member/ApplyDetail.js
  src/pages/member/ApplyRegist.js
  src/pages/member/ApplySeller.js
  src/pages/member/Signup.js
  src/utils/FormatDateUtil.js
Labels: ✨feat

#86 #85 관리자페이지 신규 입점 조회/승인/거절
  src/App.js
  src/apis/ApplyAPICalls.js
  src/modules/ApplyModules.js
  src/modules/MemberModules.js
  src/pages/admin/AdminApplyDetail.js
  src/pages/admin/AdminApplyList.js
Labels: ✨feat

#89 Feat/#58 member inquiry view
  src/App.js
  src/apis/InquiryAPI.js
  src/pages/Inquiry/member/InquiryListView.js
  src/pages/Inquiry/member/InquiryMain.js
  src/pages/Inquiry/member/InquiryRegist.js
  src/pages/Inquiry/member/InquiryUpdate.js
Labels: 🐞bug

#91 #90 관리자 공지사항 등록
  src/apis/NoticeAPICalls.js
  src/components/common/AdminPageNavBar.js
  src/components/common/PagingBar.js
  src/components/common/UserPageNavBar.js
  src/layouts/UserPageLayout.js
  src/modules/NoticeModules.js
  src/pages/admin/AdminCreateNotice.js
  src/pages/admin/AdminReport.js
  src/pages/admin/AdminUpdateNotice.js
  src/pages/admin/Notice.js
  src/pages/admin/Notices.js
  src/pages/member/MemberProfile.js
  src/pages/seller/MyStoreList.js
  src/style.css
Labels: ✨feat, 🔨refactor

#94 #58 문의 조회 성공
  src/apis/InquiryAPI.js
  src/components/items/inquiry/InquiryListItem.js
  src/pages/Inquiry/member/InquiryListView.js
  src/pages/Inquiry/member/InquiryMain.js
  src/pages/Inquiry/member/InquiryRegist.js
Labels: ✨feat

#96 #58 등록된 문의 조회
  src/components/items/inquiry/InquiryListItem.js
  src/style.css
Labels: 🐞bug

#93 [Feature] 공지사항 수정
  src/App.js
  src/components/common/NavBar.js
  src/components/items/MainItem.js
  src/pages/admin/AdminCreateNotice.js
  src/pages/admin/AdminUpdateNotice.js
  src/pages/admin/Notices.js
Labels: ✨feat

#98 #87 판매자 스토어 정보 수정 / 신규 등록 / 운영 정지
  src/App.js
  src/apis/SellerAPICalls.js
  src/components/items/StoreProfile.js
  src/components/items/StoreProfileItem.js
  src/modules/SellerModules.js
  src/modules/index.js
  src/pages/seller/MyStoreList.js
  src/pages/seller/StoreProfile.js
  src/style.css
Labels: ✨feat, 🔨refactor

#103 #102 공통 파일 개선
  src/App.js
  src/modules/index.js
Labels: 🔨refactor

#110 [Feature] 리뷰 상세조회
  src/App.js
  src/apis/NoticeAPICalls.js
  src/components/common/PagingBar.js
  src/components/items/ReportButton.js
  src/pages/ReviewDetail.js
  src/pages/Reviews.js
  src/pages/admin/AdminReport.js
  src/pages/admin/Notices.js
  src/style.css
Labels: ✨feat

#111 #106 회원가입 이메일 본인인증 기능
  src/App.js
  src/apis/MemberAPICalls.js
  src/components/form/SignupForm.js
  src/components/items/SuccessPage.js
  src/modules/MemberModules.js
  src/pages/seller/MyStoreList.js
  src/pages/verification/VerifySuccess.js
Labels: ✨feat, 🔨refactor

#115 #112 판매자 전환 및 상단바 기능 수정
  .gitignore
  src/App.js
  src/components/common/NavBar.js
  src/components/common/SellerPageNavBar.js
  src/components/common/UserPageNavBar.js
  src/layouts/SellerPageLayout.js
  src/layouts/UserPageLayout.js
  src/layouts/common/Layout.js
  src/pages/Main.js
  src/pages/MainItem.js
Labels: ✨feat, 🔨refactor

#116 #95 회원, 스토어 주문 내역 조회 및 스토어 주문 처리
  src/App.js
  src/apis/AddressAPICalls.js
  src/apis/OrderAPICalls.js
  src/components/common/SellerPageNavBar.js
  src/components/common/SortDropdown.js
  src/components/common/StatusButton.js
  src/components/common/UserPageNavBar.js
  src/components/items/AddressSelectionModal.js
  src/components/items/CouponSelector.js
  src/components/items/DeliveryAddressModal.js
  src/components/items/DeliveryInfo.js
  src/components/items/DeliveryModal.js
  src/components/items/Order.js
  src/components/items/OrderItem.js
  src/components/items/OrderItems.js
  src/components/items/OrderSummary.js
  src/components/items/StatusTracker.js
  src/components/items/Summary.js
  src/modules/AddressModules.js
  src/modules/index.js
  src/pages/order/MemberOrderDetails.js
  src/pages/order/MemberOrderList.js
  src/pages/order/Order.js
  src/pages/order/OrderApprovalHandler.js
  src/pages/order/OrderDetails.js
  src/pages/order/OrderList.js
  src/pages/order/OrderRegistration.js
  src/pages/order/OrderShippingHandler.js
  src/pages/order/StoreOrderDetails.js
  src/pages/order/StoreOrderList.js
  src/style.css
Labels: ✨feat

#117 #87 스토어 운영 정지 기능 개선 및 해제 기능 구현
  src/apis/SellerAPICalls.js
  src/pages/seller/StoreProfile.js
Labels: ✨feat, 🔨refactor

#118 #99 멤버 문의 목록 조회 디버깅
  src/App.js
  src/apis/InquiryAPI.js
  src/components/items/inquiry/InquiryListItem.js
  src/components/list/InquiryList.js
  src/pages/Inquiry/InquiryDetail.js
  src/pages/Inquiry/InquiryListView.js
  src/pages/Inquiry/InquiryMain.js
  src/pages/Inquiry/InquiryRegist.js
Labels: 🐞bug

#119 #99 구동오류 해결
  src/App.js
  src/pages/Inquiry/InquiryDetail.js
Labels: 🐞bug

#120 #99 회원 문의 상세 페이지 연동
  src/App.js
  src/apis/InquiryAPI.js
  src/components/items/inquiry/InquiryListItem.js
  src/modules/InquiryModules.js
  src/pages/Inquiry/InquiryDetail.js
  src/pages/Inquiry/InquiryMain.js
  src/pages/Inquiry/InquiryRegist.js
  src/style.css
Labels: 🎨React/CSS

#121 #99 문의 상세 보기
  src/pages/Inquiry/InquiryDetail.js
Labels: ✨feat

#122 #108 상품 관리 기능 관련 페이지
  src/App.js
  src/apis/ProductAPI.js
  src/components/form/ProductDescriptionForm.js
  src/components/form/ProductForm.js
  src/components/form/ProductOptionEditForm.js
  src/components/items/MystoreProductItem.js
  src/components/items/ProductItem.js
  src/modules/ProductModules.js
  src/modules/index.js
  src/pages/product/ProductDetail.js
  src/pages/seller/MyStoreList.js
  src/pages/seller/ProductEdit.js
  src/pages/seller/ProductManagement.js
  src/pages/seller/ProductRegist.js
Labels: ✨feat

#124 #123 상품 관련 페이지 ui 수정
  public/bannerimg1.jpg
  public/bannerimg2.png
  public/defaultImg.png
  src/apis/ProductAPI.js
  src/components/form/ProductDescriptionForm.js
  src/components/form/ProductForm.js
  src/components/form/ProductOptionAddForm.js
  src/components/items/MystoreProductItem.js
  src/components/items/ProductDetailItem.js
  src/components/items/ProductItem.js
  src/components/items/StoreBanner.js
  src/pages/Reviews.js
  src/pages/seller/ProductRegist.js
  src/style.css
Labels: 🎨React/CSS, 🔨refactor

#128 #127 주문 등록, 결제 연결 및 주문 내역 필터링 추가
  src/apis/AddressAPICalls.js
  src/apis/OrderAPICalls.js
  src/components/items/DeliveryAddressModal.js
  src/components/items/DeliveryInfo.js
  src/components/items/OrderItems.js
  src/components/items/OrderSummary.js
  src/components/items/RejectOrderModal.js
  src/pages/order/MemberOrderDetails.js
  src/pages/order/MemberOrderList.js
  src/pages/order/OrderApprovalHandler.js
  src/pages/order/OrderRegistration.js
  src/pages/order/OrderShippingHandler.js
  src/pages/payment/CheckoutPage.js
  src/pages/payment/SuccessPage.js
Labels: 🔨refactor

#131 #130 상품 옵션 목록 API 호출 기능 재추가
  src/apis/ProductAPI.js
Labels: 🐞bug
