Repository team-yeo-eun-pa/greenFire-frontend, pull requests merged in 2024-05, with the labels that each got.

#8 #5 상품 목록 페이지 작성
  .idea/.gitignore
  .idea/greenFire-frontend.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/components/common/NavBar.js
  src/components/items/ArrangeDrop.js
  src/components/items/ProductItem.js
  src/components/items/StoreBanner.js
  src/pages/product/ProductMain.js
  src/style.css
Labels: ✨기능

#13 #12 리액트 기본 설정
  .env
  src/apis/MemberAPICalls.js
  src/apis/api.js
  src/modules/index.js
  src/store.js
  src/utils/TokenUtils.js
Labels: ⚙설정

#14 #3 회원가입 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/components/common/NavBar.js
  src/components/form/SignupForm.js
  src/custom.scss
  src/index.js
  src/modules/MemberModules.js
  src/modules/index.js
  src/pages/member/Signup.js
Labels: ✨기능, 🎨React/CSS

#19 #11 상품 등록 페이지 작성
  package-lock.json
  package.json
  src/App.js
  src/components/common/SellerPageNavBar.js
  src/components/form/ProductOptionForm.js
  src/components/items/TextEditor.js
  src/components/items/TextEditorModules.js
  src/components/items/WishItem.js
  src/custom.scss
  src/index.js
  src/modules/ProductModules.js
  src/pages/seller/ProductEdit.js
  src/pages/seller/ProductManagement.js
  src/pages/seller/ProductRegist.js
  src/style.css
Labels: ✨기능, 🎨React/CSS

#18 #15 회원가입 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/apis/MemberAPICalls.js
  src/apis/api.js
  src/components/common/NavBar.js
  src/components/form/SignupForm.js
  src/modules/MemberModules.js
  src/modules/index.js
  src/pages/member/Signup.js
Labels: ✨기능

#22 #20 로그인 모달창 구현
  public/logo_horizontal.png
  src/components/common/NavBar.js
  src/components/items/LoginModal.js
Labels: 🎨React/CSS

#26 #24 로그인 기능 구현
  src/App.js
  src/apis/MemberAPICalls.js
  src/apis/api.js
  src/components/common/NavBar.js
  src/components/items/LoginModal.js
  src/utils/TokenUtils.js
Labels: ✨기능

#28 #16 cs center view-main
  package-lock.json
  package.json
  src/App.js
  src/apis/Challenge/InquiryAPI.js
  src/components/common/CustomComponents.js
  src/components/common/NavBar.js
  src/components/common/SellerPageNavBar.js
  src/components/common/challenge/list/InquiryList.js
  src/components/items/challenge/InquiryItem.js
  src/components/items/challenge/InquiryListItem.js
  src/components/items/common/ArrangeDrop.js
  src/components/items/common/ChallengeItem.js
  src/components/items/common/ListGroutEx.js
  src/components/items/common/ProductItem.js
  src/components/items/common/StoreBanner.js
  src/components/items/common/TableEx.js
  src/components/items/common/WishItem.js
  src/components/items/common/WishToCartModal.js
  src/modules/InquiryModules.js
  src/modules/index.js
  src/pages/Inquiry/InquiryDetail.js
  src/pages/Inquiry/InquiryMain.js
  src/pages/challenge/ChallengeMain.js
  src/pages/product/ProductMain.js
  src/pages/product/Wishlist.js
Labels: ✨기능, 🎨React/CSS

#35 #34 관리자 공지사항 조회 완료
  .env
  package-lock.json
  package.json
  src/App.js
  src/apis/AdminNoticeAPICalls.js
  src/components/common/AdminPageNavBar.js
  src/layouts/AdminPageLayout.js
  src/modules/NoticeModules.js
  src/modules/index.js
  src/pages/admin/AdminNotice.js
  src/pages/admin/AdminNotices.js
  src/store.js
Labels: ✨기능
